### ISSUE TITLE
Rémunération à la journée 

### ISSUE THREAD

**Issue by vincentux** [duniter/remuniter#5]
Est-il possible de forcer REMUNITER a nous payer qu'une fois par jour,
 afin d'éviter un historique a n'en plus finir ;)

![capture05](https://cloud.githubusercontent.com/assets/11737560/22426064/2ad7df14-e6fe-11e6-9687-7d00fe337d0b.PNG)

**Comment by c-geek** [comment]
Oui, on peut même faire plus :-) Je vais mettre tous les 2 jours pour être tranquilles.

**Comment by Insoleet** [comment]
C'est dommage ça permettait de générer plein de tx sur le réseau :) C'était plutôt pratique pour tester.

**Comment by c-geek** [comment]
Bizarre, la période était passée à 95 blocs soit loin de mes 2 jours ... j'ai tenté de relancer pour 576 blocs (2 jours) en forçant, on verra.
