### ISSUE TITLE
Language display

### ISSUE THREAD

**Issue by gpsqueeek** [duniter/remuniter#8]
The "last gifs" section should be renamed "last gifts" in the english version.
By the way, I see the interface in French on my English-configured PC but in English on my French-configured PC. Can we choose or is it linked to the IP address maybe ? Or it uses the system language and the logic is reversed ?
Thanks !

**Comment by M5oul** [comment]
Typo is already fixed on https://github.com/duniter/remuniter/commit/ee216bf1696d1e9e5af294403cbc31e4638ea3b9.

**Comment by gpsqueeek** [comment]
You guys are too fast, stop using time machines please :-)
